linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: emperror.dev/handler/bugsnag

linters:
    enable-all: true
    disable:
        - funlen
        - gomnd
        - testpackage
